#!/usr/bin/env python3
"""
SmartSupport Document Upload Demo
Ingests sample Machine Learning documents into Endee vector database.
Users should then open chat.html to ask questions about these documents.

Usage:
    python demo.py
"""

from src.rag_engine import RAGEngine

# ── Machine Learning Sample Documents ──────────────────────────
SAMPLE_DOCS = [
    (
        "machine_learning_basics.txt",
        """
        Machine Learning Basics

        Machine Learning (ML) is a branch of artificial intelligence that enables 
        systems to learn and improve from experience without being explicitly programmed. 
        It focuses on developing computer programs that can access data and use it to 
        learn for themselves.

        The learning process begins with observations or data, such as examples, direct 
        experience, or instruction, in order to look for patterns in data and make better 
        decisions in the future based on the examples that we provide.

        Key Components of ML:
        - Data: The raw material that ML algorithms learn from
        - Features: The specific measurable properties of data
        - Model: The mathematical representation of patterns learned from data
        - Algorithm: The procedure for training the model
        - Prediction: The output generated by the trained model

        ML has three main paradigms:
        1. Supervised learning: Learning from labeled data
        2. Unsupervised learning: Finding patterns in unlabeled data
        3. Reinforcement learning: Learning through interaction and rewards

        Applications of ML include: recommendation systems, image recognition, natural 
        language processing, fraud detection, medical diagnosis, autonomous vehicles, 
        and predictive analytics.
        """,
    ),
    (
        "deep_learning_guide.txt",
        """
        Deep Learning Guide

        Deep learning is a specialized branch of machine learning that uses algorithms 
        inspired by the structure and function of biological neural networks, called 
        artificial neural networks (ANNs). The "deep" in deep learning refers to multiple 
        layers in these neural networks.

        Neural Networks:
        Neural networks consist of interconnected nodes (neurons) organized in layers:
        - Input layer: Receives raw input data
        - Hidden layers: Process information through weighted connections
        - Output layer: Produces the final prediction

        Key Deep Learning Architectures:
        
        1. Convolutional Neural Networks (CNNs): Specialized for image processing and 
           computer vision. They use convolutional layers to detect features at multiple 
           scales.

        2. Recurrent Neural Networks (RNNs): Designed for sequential data like time series 
           and text. They maintain internal state and can process variable-length sequences.

        3. Transformers: Revolutionary architecture using attention mechanisms, enabling 
           parallel processing and better long-range dependencies. Foundation of modern 
           language models.

        4. Generative Adversarial Networks (GANs): Two networks competing - generator 
           creates synthetic data, discriminator evaluates authenticity.

        Deep learning excels at:
        - Image classification and object detection
        - Natural language understanding and generation
        - Speech recognition and synthesis
        - Time series forecasting
        - Anomaly detection

        Popular frameworks include TensorFlow, PyTorch, and Keras, which provide high-level 
        APIs and GPU acceleration for training large models.
        """,
    ),
    (
        "nlp_fundamentals.txt",
        """
        Natural Language Processing Fundamentals

        Natural Language Processing (NLP) is a subfield of artificial intelligence that 
        focuses on enabling computers to understand, interpret, and generate human language 
        in a meaningful and useful way. It bridges the gap between human communication and 
        computer understanding.

        Core NLP Tasks:

        1. Tokenization: Breaking text into individual words or subwords
        2. Part-of-Speech Tagging: Identifying nouns, verbs, adjectives, etc.
        3. Named Entity Recognition (NER): Identifying people, places, organizations
        4. Sentiment Analysis: Determining emotions and opinions in text
        5. Machine Translation: Converting text from one language to another
        6. Question Answering: Extracting answers from documents given questions
        7. Text Summarization: Condensing long documents into summaries
        8. Semantic Similarity: Measuring how similar two texts are in meaning

        Traditional NLP Approaches:
        - Rule-based systems: Use hand-crafted linguistic rules
        - Statistical methods: Learn patterns from labeled data
        - Feature engineering: Manually create relevant features

        Modern NLP with Deep Learning:
        - Word embeddings (Word2Vec, GloVe): Represent words as dense vectors
        - Recurrent neural networks: Process sequences of words
        - Transformer models: Parallel processing with attention mechanisms
        - Pre-trained language models: Transfer learning from large text corpora

        Applications include:
        - Virtual assistants and chatbots
        - Email spam detection
        - Automatic document classification
        - Information extraction
        - Speech recognition and synthesis
        - Auto-complete and predictive text
        """,
    ),
    (
        "supervised_learning_explained.txt",
        """
        Supervised Learning Explained

        Supervised learning is a machine learning paradigm where the algorithm learns 
        from labeled training data. Each training example consists of an input (features) 
        and a corresponding output (label or target). The goal is to learn a function 
        that maps inputs to outputs accurately.

        Key Characteristics:
        - Requires labeled training data (inputs with known outputs)
        - Learns a mapping function: y = f(x)
        - Model is evaluated on holdout test set
        - More data generally improves performance

        Main Types of Supervised Learning:

        Classification:
        Predicting categorical outputs (discrete classes). Examples:
        - Email spam detection (spam vs. not spam)
        - Image classification (cat, dog, bird, etc.)
        - Medical diagnosis (disease vs. no disease)
        
        Common algorithms: Logistic Regression, Decision Trees, Random Forest, 
        Support Vector Machines (SVM), Naive Bayes

        Regression:
        Predicting continuous numerical outputs. Examples:
        - House price prediction
        - Stock price forecasting
        - Temperature prediction
        
        Common algorithms: Linear Regression, Polynomial Regression, Ridge Regression, 
        Lasso Regression, Support Vector Regression

        Workflow:
        1. Collect and label training data
        2. Split data into training and test sets
        3. Choose and train a model
        4. Evaluate on test set using metrics (accuracy, precision, recall, F1-score)
        5. Tune hyperparameters to improve performance
        6. Deploy model for predictions on new, unseen data

        Challenges:
        - Requires expensive manual labeling
        - Overfitting when model memorizes training data
        - Class imbalance in classification problems
        - Need for high-quality labeled data
        """,
    ),
    (
        "unsupervised_learning_techniques.txt",
        """
        Unsupervised Learning Techniques

        Unsupervised learning is a machine learning paradigm where the algorithm learns 
        patterns from unlabeled data without predefined outputs. The goal is to discover 
        hidden structures, relationships, or patterns in the data.

        Key Characteristics:
        - No labeled target variable
        - Explores inherent structure in data
        - Useful for exploratory data analysis
        - Often used for preprocessing or feature extraction

        Main Types of Unsupervised Learning:

        Clustering:
        Grouping similar data points together. The algorithm finds natural groupings:
        
        - K-Means: Partitions data into K clusters by minimizing within-cluster variance
        - Hierarchical Clustering: Creates tree structure of nested clusters
        - DBSCAN: Finds clusters of arbitrary shape based on density
        - Gaussian Mixture Models: Probabilistic model assuming data from K Gaussians
        
        Applications: Customer segmentation, document organization, gene sequencing

        Dimensionality Reduction:
        Reducing number of features while preserving important information:
        
        - Principal Component Analysis (PCA): Projects data onto principal components
        - t-SNE: Visualizes high-dimensional data in 2D/3D
        - Autoencoders: Neural networks that learn compressed representations
        - Feature Selection: Choosing relevant subset of features
        
        Applications: Data visualization, noise reduction, computational efficiency

        Anomaly Detection:
        Identifying unusual or outlier patterns in data:
        
        - Statistical methods: Flag points far from distribution
        - Isolation Forest: Isolates anomalies by random partitioning
        - LOF (Local Outlier Factor): Compares density to neighbors
        
        Applications: Fraud detection, system monitoring, quality control

        Association Rule Learning:
        Finding relationships between variables:
        
        - Apriori: Finds frequent itemsets in transaction data
        - Eclat: Depth-first search approach
        - Frequent Pattern Growth: Efficient pattern mining
        
        Applications: Market basket analysis, recommendation systems

        Workflow:
        1. Collect unlabeled data
        2. Preprocess and normalize data
        3. Choose unsupervised algorithm and parameters
        4. Train model on data
        5. Evaluate using metrics (silhouette score, elbow method, etc.)
        6. Interpret and visualize discovered patterns
        7. Use insights for business decisions

        Challenges:
        - Evaluation is subjective without ground truth labels
        - Difficulty determining optimal number of clusters
        - Computational complexity with large datasets
        - Sensitive to preprocessing and parameter choices
        """,
    ),
]


def upload_documents():
    """Upload sample ML documents to Endee vector database."""
    print("\n" + "═" * 60)
    print("  SmartSupport — Document Upload Demo")
    print("  Machine Learning Sample Dataset")
    print("═" * 60)

    # Initialise RAG engine
    print("\n[1/2] Initialising RAG engine …")
    rag = RAGEngine()
    print("  ✓ Connected to Endee vector database")

    # Ingest sample documents
    print("\n[2/2] Uploading Machine Learning documents …\n")
    for filename, text in SAMPLE_DOCS:
        result = rag.ingest_text(text, filename=filename)
        print(f"  ✓ {result['filename']:<35} ({result['num_chunks']:>2} chunks, id={result['doc_id']})")

    print("\n" + "═" * 60)
    print("  Upload complete!")
    print("\n  📖 Next Steps:")
    print("     1. Open chat.html in your web browser")
    print("     2. Start asking questions about Machine Learning")
    print("     3. The system will retrieve relevant documents and")
    print("        provide grounded answers with source citations")
    print("═" * 60 + "\n")


if __name__ == "__main__":
    upload_documents()
